### ISSUE TITLE
Zoom Out button hidden on iOS Safari

### ISSUE THREAD

**Issue by kyledrowan** [kyledrowan/historikc-rails#7]

**Comment by Snailslug** [comment]
Can you just not display the zoom buttons for mobile? It's probably not even needed and pinch is a ubiquitous gesture.

**Comment by kyledrowan** [comment]
@Snailslug probably could have disabled the buttons, but for consistency with desktop (and an assumption that there will be quite a few older users..) I moved from using css to js for height
